---
- name: fetch repository keys from keyservers
  rpm_key:
    state: "{{ item.state | default('present') }}"
    key: 'https://keyserver.opensuse.org/pks/lookup?op=get&search={{ item.id }}'
  with_items: "{{ repository_keys }}"
  when: item.url is not defined
  become: true
  become_user: root
  tags:
    - install
    - config

- name: fetch repository keys from URLs
  rpm_key:
    state: "{{ item.state | default('present') }}"
    key: "{{ item.url }}"
  with_items: "{{ repository_keys }}"
  when: item.url is defined
  become: true
  become_user: root
  tags:
    - install
    - config

- name: configure repositories
  zypper_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state | default('present') }}"
    name: "{{ item.name | default(omit) }}"
  with_items: "{{ repositories }}"
  become: true
  become_user: root
  tags:
    - install
    - config
    - upgrade

- name: update package cache
  zypper_repository:
    repo: '*'
    runrefresh: yes
  become: true
  become_user: root
  tags:
    - install
    - upgrade

- name: install packages
  package:
    name: "{{ item.name }}"
    state: "{{ item.state | default(package_state) }}"
    disable_recommends: yes
  with_items: "{{ packages }}"
  become: true
  become_user: root
  tags:
    - install

- name: upgrade packages
  package:
    name: '*'
    state: dist-upgrade
  become: true
  become_user: root
  tags:
    - install
    - upgrade
