---
- hosts: all
  tasks:
    - group_by: key={{ ansible_distribution|lower }}
      changed_when: false
    - group_by: key={{ ansible_os_family|lower }}
      changed_when: false
  tags:
    - always

- include: ubuntu.yml

- include: opensuse.yml

- include: debian.yml
