- hosts: ubuntu
  roles:
    - role: ubuntu.common
      tags: common
    - role: ubuntu.pam
      tags: pam

- hosts: "&ubuntu:lxc"
  roles:
    - role: ubuntu.lxc
      tags: lxc

- hosts: "&ubuntu:nm"
  roles:
    - role: ubuntu.nm
      tags: nm

- hosts: "&ubuntu:nodejs"
  roles:
    - role: ubuntu.nodejs
      tags: nodejs

- hosts: "&ubuntu:ufw"
  roles:
    - role: ubuntu.ufw
      tags: ufw
