- hosts: ubuntu
  sudo: yes
  roles:
    - ubuntu.common

- hosts: "&ubuntu:lxc"
  roles:
    - role: ubuntu.lxc
      tags: lxc

- hosts: "&ubuntu:nm"
  roles:
    - role: ubuntu.nm
      tags: nm

- hosts: "&ubuntu:nodejs"
  roles:
    - role: ubuntu.nodejs
      tags: nodejs

- hosts: "&ubuntu:python"
  roles:
    - role: ubuntu.python
      tags: python
