- hosts: ubuntu
  roles:
    - role: ubuntu
      tags: common
    - role: ubuntu.pam
      tags: pam

- hosts: "&ubuntu:python"
  roles:
    - role: ubuntu.python
      tags: python

- hosts: "&ubuntu:lxc"
  roles:
    - role: ubuntu.lxc
      tags: lxc

- hosts: "&ubuntu:nm"
  roles:
    - role: ubuntu.nm
      tags: nm

- hosts: "&ubuntu:nodejs"
  roles:
    - role: ubuntu.nodejs
      tags: nodejs

- hosts: "&ubuntu:ufw"
  roles:
    - role: ubuntu.ufw
      tags: ufw

- hosts: "&ubuntu:emacs"
  roles:
    - role: ubuntu.emacs
      tags: emacs

- hosts: "&ubuntu:git"
  roles:
    - role: ubuntu.git
      tags: git

- hosts: "&ubuntu:yubikey"
  roles:
    - role: ubuntu.yubikey
      tags: yubikey
