packages: []
repositories: []
repository_keys: []
keyserver: 'keys.ubuntu.com'
package_state: 'present'
modules: []
blacklist_modules: []
services: []
volume_groups: []
filesystems: []
files: []
users: []
package_upgrade: safe
package_architectures: []
sysctls: []
ufw_policies: []
ufw_rules: []
