---
- name: create NM system connections
  template:
    src: system-connection.j2
    dest: "/etc/NetworkManager/system-connections/{{ item.key }}"
    owner: root
    group: root
    mode: '0600'
  with_dict: "{{ nm_system_connections }}"
  become: true
  become_user: root
  tags: config
  notify: 
    - restart network-manager
