---
- name: install git package
  apt:
    name: git
    state: installed
  become: true
  become_user: root
  tags:
    - install

- name: set global git config
  git_config:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    scope: global
  with_dict: '{{ git_global_config }}'
  tags:
    - config
