---
- name: install packages
  apt:
    name: "{{ item }}"
  with_items:
    - python-pip
    - python3-pip
    - virtualenv
    - virtualenvwrapper
  become: true
  become_user: root
  tags: install

- name: install pip packages (in virtualenvs)
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version|default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    virtualenv: "~/.virtualenvs/{{ item.virtualenv }}"
  with_items: "{{ pip_packages }}"
  become: false
  when: item.virtualenv is defined
  tags: install

- name: install pip packages (outside virtualenvs)
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version|default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    executable: "{{ item.executable|default(omit) }}"
  with_items: "{{ pip_packages }}"
  become: true
  become_user: root
  when: item.virtualenv is not defined
  tags: install
